### PR TITLE
Newsletter 236 translate in french

### PR DESCRIPTION
**Pull request by Copinmalin**

### CODE REVIEW

**Comment by Copinmalin** [comment]
Hello @bitschmidty ,

can you confirm 3 last active PR please ?

**Review by bitschmidty — COMMENTED** [review]
@Copinmalin I checked out your 'Newsletter-236-trranslate-in-french' branch locally, reset --hard to origin/master (to get the latest from master and discard any unrelated commits from your other WIPs) and then did git cherry-pick to pull out just the commits related to newsletter 236-fr and squashed them into one commit

**Comment by Copinmalin** [comment]
I'm sorry for all this stuff,
 I don't understand why sometimes it's so complicated.

From master, I create a new branch, as you ask me
after I create the new file with newsletter to translate, 
then create a PR 
and after finished translation and a good check I submit to review.

What is wrong ?

**Comment by bitschmidty** [comment]
@Copinmalin my guess is that your local master doesn’t match up with "origin/master" (from this repo). If you "git reset --hard origin/master" from your local master branch (assuming you dont have anything you’re working on there), I think that would help. Then new branches created from your local master branch would have the latest and also not have anything extraneous.

**Comment by Copinmalin** [comment]
OK So I wait for merging my last PR and do again this hard reset.

**Pull request merged**
