### PR TITLE
Newsletters: add 206 (2022-06-29)

### PR DESCRIPTION
**Pull request by harding**
- [x] Lede, releases/RCs, topic links @harding
- [x] Bitcoin Stack Exchange section @bitschmidty

### CODE REVIEW

**Comment by Xekyo** [comment]
Got anything for me this week?

**Review by Xekyo — COMMENTED** [review]
LGTM

**Comment by harding** [comment]
@Xekyo whoops, sorry, I forgot to find something for you this week.  Would you like me to give you something for next week, or would you just like an item in two weeks as per usual?  Thanks for the review!

**Comment by Xekyo** [comment]
I see. I'll just skip this one then. Thanks

**Comment by harding** [comment]
Added missing content and reviewed @bitschmidty's section.  Thanks @Xekyo and @bitschmidty!

**Comment by bitschmidty** [comment]
Thanks @harding for authoring and @Xekyo for the 👀

**Pull request merged**
