### PR TITLE
STYLE: avoid incaps and other marketing tricks

### PR DESCRIPTION
**Pull request by harding**
The goal is to avoid "branding activity that colonizes everyday communications", see the screed at https://boingboing.net/2014/01/01/newyearsresolution-avoid-inca.html

This is re: https://github.com/bitcoinops/bitcoinops.github.io/pull/999#discussion_r1094862609 and is totally up for discussion (I'd like this policy, but I'll give way if others feel strongly opposed to it).

### CODE REVIEW

**Comment by paulkania** [comment]
Thanks for raising this point.
 ACK for avoiding incap marketing tactics. e.g.  choose <Iphone/iphone> instead <iPhone>.

sqlite/SQLite is a bit of an edge case - SQL is an acronym, SQLite/sqlite is an engine in public domain, but is no longer an acronym but a franken-acronym. I'd lean towards SQLite, since it's not a blatant advertisement for anything. Could go either way.

**Comment by Xekyo** [comment]
I don’t feel strongly either way.

**Comment by LarryRuane** [comment]
Like Murch, I don't feel strongly. I wasn't aware of this problem, but the screed makes sense. ACK.

**Comment by jirijakes** [comment]
I feel this guideline would go a bit against creativity that is prevalent in Bitcoin space where many brand names are on the edge of technical terms and acronyms. If the problem with incaps is their marketing nature, subjects of the texts here are mostly all kinds of free projects that, I believe, deserve some free advertising. Only rarely are Apple products mentioned.

Lnbits, Joinmarket, Asicboost, Musig, Bitmex, Okcoin, Opentimestamps, Bitgo, Btcpay Server…

**Comment by bitschmidty** [comment]
I like the simplicity of noting a product/service/company by what they call themselves. But not in the "strongly" oppose camp.

**Comment by ajtowns** [comment]
Yuck? Certainly keep things to ascii text rather than including emojis or jpeg logos or profile pictures (and perhaps don't update if a brand changes its preferred capitalisations, and maybe circumlocute to "the software formerly known as prince" if needed), but changing `iPhone` to `Iphone` seems like just adding confusion rather than reducing it... First page of a google search for "sqlite" seems to all be capitalised as "SQLite" also.

**Comment by harding** [comment]
After discussion, I'm leaning towards using a project/organization's preferred capitalization (unless its egregious).  I'm going to leave this issue open until I update the capitalization of SQLite in Newsletter 237.

Thanks everyone for the opinions!

**Comment by petertodd** [comment]
@jirijakes 
> Lnbits, Joinmarket, Asicboost, Musig, Bitmex, Okcoin, Opentimestamps, Bitgo, Btcpay Server…

FWIW I picked the capitalization OpenTimestamps for readability, as Opentimestamps is a rather long word and the ntime bit is visually muddled without the uppercase T. So I'd suggest sticking with the standard capitalization.

(the reason why it's one word rather than two is to make it easy to search for for uses of it; exactly how I found this pull-req!)

**Pull request closed without merging**
