### PR TITLE
Newsletter-22: translate into Chinese

### PR DESCRIPTION
**Pull request by bittomhan**

### CODE REVIEW

**Comment by bittomhan** [comment]
`make preview` checked

**Comment by bittomhan** [comment]
This time, I successfully used "make preview" before "make production" and submitted it: I actually managed to see the page, but "make production" was unsuccessful.

In the future, I will continue to use "make production" after "make preview."

**Comment by bittomhan** [comment]
`make preview` checked

**Comment by bitschmidty** [comment]
@bittomhan did you mean to close this PR?

**Comment by bittomhan** [comment]
> @bittomhan did you mean to close this PR?

Hello, 

I found that there is a referenced link in this PR:
`[newsletter #12]: /zh/newsletters/2018/09/11/#workshop`
I need to wait until the "fix zh link format" PR is merged before I can correctly reference this file. Therefore, I have to temporarily close this PR until I can rebase it onto that branch.

Thank you!

**Review by bitschmidty — APPROVED** [review]
ACK, thank you @bittomhan

**Pull request merged**
