### PR TITLE
Newsletter-220: add Chinese translation

### PR DESCRIPTION
**Pull request by hulatown**

### CODE REVIEW

**Comment by hulatown** [comment]
I think the reason for the check failure is that I submit this PR (newsletter220) right after the newsletter219 got merged. So 
the auto-check didn't get the latest newsletter219-zh page, and the link check rule failed in the absence of newsletter219-zh page. And I can build successfully in local with newsletter219-zh.

@bitschmidty do you know how to fix this kind of error? Should I maybe simply submit again? Thanks very much

**Comment by bitschmidty** [comment]
@hulatown you should be able to rebase on master `git rebase origin/master`

If you give me permission to push to your repo, I can also help.

**Comment by hulatown** [comment]
> @hulatown you should be able to rebase on master `git rebase origin/master`
> 
> If you give me permission to push to your repo, I can also help.

I see. Thanks so much Mike! I thought the CI was running against the latest master branch... Will pay attention next time

**Review by bitschmidty — APPROVED** [review]
Looks good, thanks for the translation @hulatown !

**Pull request merged**
