### PR TITLE
Add Wasabi RBF notification support

### PR DESCRIPTION
**Pull request by nopara73**
PR implements it: https://github.com/zkSNACKs/WalletWasabi/pull/2670

Messages:

image

### CODE REVIEW

**Comment by MaxHillebrand** [comment]
Concept ACK. #2670 is merged, so this is no longer draft.

**Comment by bitschmidty** [comment]
Very cool @nopara73 , thanks for the PR!

Should we wait for the next release? That way I can test and also bump tested on version from version 1.1.6 to 1.1.10. Or I can go off the latest RC if you prefer?

**Comment by nopara73** [comment]
Please go with the RC: https://github.com/zkSNACKs/WalletWasabi/releases

**Comment by jnewbery** [comment]
I think the compatibility site should only include full releases, not developer branches or RCs.

**Comment by nopara73** [comment]
It makes sense. I will get back here after the release.

**Comment by nopara73** [comment]
The release is out: https://github.com/zkSNACKs/WalletWasabi/releases

**Comment by bitschmidty** [comment]
@nopara73 Great!

Since we are bumping the version from version 1.1.6 to 1.1.10 on the matrix, I also want to just make sure nothing else pertinent to the matrix changed and also grab a screenshot image of the new notification to add to this PR. Sound good?

**Comment by nopara73** [comment]
We started signalling randomly RBF for 2% of our transactions, but I guess that's insignificant, I just noted it for completeness.  

https://github.com/zkSNACKs/WalletWasabi/pull/2405

**Comment by bitschmidty** [comment]
@nopara73 Good to know on the 2% rbf signaling. Ive added that note as well as a screenshot of the new notification, and a bump to the tested on and version number. Let me know if those look ok.

**Comment by nopara73** [comment]
This is correct.

**Comment by bitschmidty** [comment]
Rebases on master. Squashed.

**Pull request merged**
