### PR TITLE
Harmonize titles of French Newsletters

### PR DESCRIPTION
**Pull request by murchandamus**
@Copinmalin: I got all the titles, except the yearly reviews aligned. What’s your favorite out of the following?

- Revue spéciale Année 2020'
- Spécial Bilan 2021'
- Spéciale Revue annuelle 2022'

--------------

Edit: all ready for review. Below is an overview of what changed

**Before**

> 2020-12-23-newsletter.md:title: 'Bulletin Bitcoin Optech #129: Revue spéciale Année 2020'
> 2021-12-22-newsletter.md:title: 'Bulletin Bitcoin Optech #180: Spécial Bilan 2021'
> 2022-09-07-newsletter.md:title: 'Bitcoin Optech Newsletter #216'
> 2022-09-14-newsletter.md:title: 'Bitcoin Optech Newsletter #217'
> 2022-09-21-newsletter.md:title: 'Bitcoin Optech Newsletter #218'
> 2022-09-28-newsletter.md:title: 'Bitcoin Optech Newsletter #219'
> 2022-10-05-newsletter.md:title: 'Bitcoin Optech Newsletter #220'
> 2022-10-12-newsletter.md:title: 'Bitcoin Optech Newsletter #221'
> 2022-10-19-newsletter.md:title: 'Bitcoin Optech Newsletter #222'
> 2022-10-26-newsletter.md:title: 'Bitcoin Optech Newsletter #223'
> 2022-11-02-newsletter.md:title: 'Bitcoin Optech Newsletter #224'
> 2022-11-09-newsletter.md:title: 'Bitcoin Optech Newsletter #225'
> 2022-11-16-newsletter.md:title: 'Bitcoin Optech Newsletter #226'
> 2022-11-23-newsletter.md:title: 'Bitcoin Optech Newsletter #227'
> 2022-11-30-newsletter.md:title: 'Bitcoin Optech Newsletter #228'
> 2022-12-07-newsletter.md:title: 'Bitcoin Optech Newsletter #229'
> 2022-12-14-newsletter.md:title: 'Bitcoin Optech Newsletter #230'
> 2022-12-21-newsletter.md:title: 'Lettre informative Bitcoin Optech #231: Spéciale Revue annuelle 2022'
> 2023-01-04-newsletter.md:title: 'Bitcoin Optech Newsletter #232'
> 2023-01-11-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #233'
> 2023-01-18-newsletter.md:title: 'Bulletin Hebdomadiare Bitcoin Optech #234'
> 2023-01-25-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #235'
> 2023-02-01-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #236'
> 2023-02-08-newsletter.md:title: 'Bulletin Bitcoin Optech #237'
> 2023-02-15-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #238'
> 2023-02-22-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #239'
> 2023-03-01-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #240'
> 2023-03-08-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #241'
> 2023-03-15-newsletter.md:title: 'Bulletin hebdomadaire Bitcoin Optech #242'
> 2023-03-22-newsletter.md:title: 'Bulletin Bitcoin Optech #243'
> 2023-03-29-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #244'
> 2023-04-05-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #245'
> 2023-04-12-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #246'
> 2023-04-19-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #247'
> 2023-04-26-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #248'
> 2023-05-03-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #249'
> 2023-05-10-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #250'
> 2023-05-17-newsletter.md:title: 'Bulletin Hebdomadaire Optech #251'
> 2023-05-24-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #252'
> 2023-05-31-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #253'
> 2023-06-07-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #254'
> 2023-06-14-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #255'
> 2023-06-21-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #256'

**After**

> 2020-12-23-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #129: Revue Spéciale Année 2020'
> 2021-12-22-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #180: Revue Spéciale Année 2021'
> 2022-09-07-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #216'
> 2022-09-14-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #217'
> 2022-09-21-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #218'
> 2022-09-28-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #219'
> 2022-10-05-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #220'
> 2022-10-12-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #221'
> 2022-10-19-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #222'
> 2022-10-26-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #223'
> 2022-11-02-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #224'
> 2022-11-09-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #225'
> 2022-11-16-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #226'
> 2022-11-23-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #227'
> 2022-11-30-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #228'
> 2022-12-07-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #229'
> 2022-12-14-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #230'
> 2022-12-21-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #231: Revue Spéciale Année 2022'
> 2023-01-04-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #232'
> 2023-01-11-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #233'
> 2023-01-18-newsletter.md:title: 'Bulletin Hebdomadiare Bitcoin Optech #234'
> 2023-01-25-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #235'
> 2023-02-01-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #236'
> 2023-02-08-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #237'
> 2023-02-15-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #238'
> 2023-02-22-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #239'
> 2023-03-01-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #240'
> 2023-03-08-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #241'
> 2023-03-15-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #242'
> 2023-03-22-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #243'
> 2023-03-29-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #244'
> 2023-04-05-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #245'
> 2023-04-12-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #246'
> 2023-04-19-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #247'
> 2023-04-26-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #248'
> 2023-05-03-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #249'
> 2023-05-10-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #250'
> 2023-05-17-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #251'
> 2023-05-24-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #252'
> 2023-05-31-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #253'
> 2023-06-07-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #254'
> 2023-06-14-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #255'
> 2023-06-21-newsletter.md:title: 'Bulletin Hebdomadaire Bitcoin Optech #256'

### CODE REVIEW

**Comment by murchandamus** [comment]
Made it a draft while waiting for input on the yearly reviews.

**Comment by Copinmalin** [comment]
Thanks for your help, seem so easy when you do it, crazy :-D 

I think "Revue spéciale Année 2020'" seem a good choice.

**Comment by murchandamus** [comment]
> I think "Revue spéciale Année 2020'" seem a good choice.

I changed all three to “Revue Spéciale Année 202X”.

> Thanks for your help, seem so easy when you do it, crazy :-D

Thanks! Sometimes knowing certain command line tools feels like having a cheatcode ;)

-----------

Ready for review

**Review by bitschmidty — APPROVED** [review]
ACK, thank you @murchandamus !

**Pull request merged**
