### PR TITLE
News112 Bitcoin Core PRs 14582/19473

### PR DESCRIPTION
**Pull request by jonatack**
WIP first draft -- might be a bit long. Will re-review tomorrow.

### CODE REVIEW

**Comment by jnewbery** [comment]
Jon, I think you should be able to push your commits directly to Dave's branch.

**Comment by jonatack** [comment]
GitHub responds with: 

```
ERROR: Permission to bitcoinops/bitcoinops.github.io.git denied to jonatack.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by jonatack** [comment]
Perhaps the wrong email was added? I have a gmail as well but `jon@atack.com` should be the right one.

**Comment by jonatack** [comment]
Found the invitation email; will push directly to the branch.

**Pull request closed without merging**
