### PR TITLE
style: reduce margin above h2 elements

### PR DESCRIPTION
**Pull request by jnewbery**

### CODE REVIEW

**Comment by jnewbery** [comment]
@moneyball - do you think this is an improvement and resolves #33 for you?

**Comment by moneyball** [comment]
It definitely improves the spacing so for that I tACK.

Separately though, I note that "Posts" font is larger than "Member Companies" and "Founding Sponsors" font, even though I checked and all are H2. I even modified the text "Posts" to "Member Companies" just to make sure my eyes weren't playing tricks on me but it is definitely bigger. Did you want to fix this in this PR or a separate one? I'd fix it but don't see how to.

**Comment by jnewbery** [comment]
The *Posts* header is using the standard minima style:

```
.post-list-heading {
  @include relative-font-size(1.75);
}
```

I can remove that class from the Posts header to get it the same size.

**Comment by jnewbery** [comment]
@moneyball - please test with the latest commit and let me know what you think.

**Pull request merged**
