### PR TITLE
Add sponsors to index page

### PR DESCRIPTION
**Pull request by jnewbery**
This adds our sponsors to the home page.

### CODE REVIEW

**Comment by jnewbery** [comment]
@harding - this adds the data, but it doesn't look very good yet!

It'd be nice if we could have the sponsors presented in a grid, similar to how the contributors were shown in bitcoincore.org prior to https://github.com/bitcoin-core/bitcoincore.org/commit/c8618b1359005d78b584c95b73d3856a84c52736. Is that possible within the minimal jekyll theme that we're using?

**Comment by jnewbery** [comment]
I've added fontawesome to address the comment here: https://github.com/bitcoinops/bitcoinops.github.io/pull/10#issuecomment-401208913 . @harding - do the last two commits look like the right approach?

I'm still waiting to get a good quote from Wences, and probably also update the quote from Chaincode.

**Comment by harding** [comment]
@jnewbery LGTM with one suggestion:

```diff
diff --git a/assets/css/main.scss b/assets/css/main.scss
index 6e2907b..91a0511 100644
--- a/assets/css/main.scss
+++ b/assets/css/main.scss
@@ -34,11 +34,13 @@ br.clear {
 
 p.sponsor-quote {
         font-style: italic;
+        margin-top: 20px;
 }
 
 .sponsors h3 {
         font-weight: 700;
         font-size: 120%;
+        margin-bottom: 0;
 }
 
 // The long text quotes make this application of a two-column list
```

Currently it's,

```text
Name

Twitter
Paragraph of text
```

This makes it,

```
Name
Twitter link

Paragraph of text
```

Which seems more natural to me.

**Comment by jnewbery** [comment]
rebased

**Comment by jnewbery** [comment]
I have approval for all three quotes from the sponsors, so I think this is ready for merge.

@harding / @moneyball - are you happy for this to go in?

**Pull request merged**
