### PR TITLE
Compatibility page tweaks

### PR DESCRIPTION
**Pull request by harding**
Here are a few small tweaks to the compatibility page CSS and generation code (not specific wallets).  Individual commit comments describe the motivation when it's not obvious.

### CODE REVIEW

**Comment by jnewbery** [comment]
harding: can you take the commit 1a01f7da7f3ae0e93d5e8a17c37f55211990d2a4 from https://github.com/bitcoinops/bitcoinops.github.io/pull/187 here if you agree with it.

**Comment by harding** [comment]
@jnewbery I cherry picked @bitschmidty's commit.

**Comment by harding** [comment]
Pushed a commit that drops the colored underlining and replaces it with colored and styled bullet points (blue checkmark and yellow X, the same as in the table view, and a grey ≈ for neutral).  Preview: https://deploy-preview-189--bitcoinops.netlify.com/en/compatibility/bitcoin-core/

**Comment by bitschmidty** [comment]
@harding I think that looks really great. Easier to see wrt colors and the icon reinforces it.

**Comment by bitschmidty** [comment]
Pushed a commit that removes the segwit v1 tests results from the compatibility templates.

**Comment by adamjonas** [comment]
This looks great @harding. Big improvement.

**Comment by harding** [comment]
Added a commit that adds links to the RBF and segwit address sections to each detail page.

**Comment by jnewbery** [comment]
I have one issue with the _compatibility: added more definition to 'Not tested' texts_ commit. I think the phrasing the statements in the affirmative (eg **Not tested: notification notes RBF**) could be confusing for someone skimming the page:

image

I've added a final commit that changes those affirmitive statements into questions (eg **Does transaction notification show whether transaction signals RBF?**):

image

@bitschmidty - does that change look good to you? If so, I'm happy to merge this PR.

**Comment by bitschmidty** [comment]
@jnewbery looks good, thanks for that!

**Pull request merged**
