### PR TITLE
Merge local commit with master

### PR DESCRIPTION
**Pull request by Copinmalin**

### CODE REVIEW

**Comment by Copinmalin** [comment]
Hello @bitschmidty , can you accept this PR, because repository has some commit in late.
Or may be I need to do something other ?

**Comment by Xekyo** [comment]
I don’t know what you’re trying to do, but this PR has an empty changeset with `bitcoinops:master`, all the changes you want to push are already in the project’s main branch.

Are you sure you have fetched the latest state of the main repository?

**Comment by Copinmalin** [comment]
Hey @Xekyo , thanks for your help.

I have this information, and I don't know how to resolve this conflict 
Capture d'écran 2023-02-22 203223

I'm up to date, no work in progress.

**Comment by Xekyo** [comment]
I think the issue is that you pulled `bitcoinops:master` into your own branch which created some merge commits. Since the same commit will have a different hash if it has a different ancestry, all the commits that you added in your local repository after the merge commit appear as new respective to the upstream repository. I suspect that you could fix that by checking out your own `master` branch and resetting it to the state of the main repository’s master branch `bitcoinops:master`:

```
git checkout master
git fetch bitcoinops
git reset --hard bitcoinops/master
git push origin master:master
```

where “bitcoinops” is a placeholder for the actual name of the main repository in your configuration, and “origin” is the name of your own remote repository. Please make sure that there are no changes you wanted to keep on your `master` branch before attempting this fix, this advice is provided without warranty. ;)

**Comment by Copinmalin** [comment]
```
git reset --hard /mnt/c/Users/cyril/OneDrive/Documents/GitHub/bitcoinops.github.io/master
fatal: ambiguous argument '/mnt/c/Users/cyril/OneDrive/Documents/GitHub/bitcoinops.github.io/master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by Xekyo** [comment]
Oh, the name that I’m referring to would be the “nickname” that the repository is known as in your local repository’s configuration.
If you’re in your local repository’s directory on your system,  presumably `/mnt/c/Users/cyril/OneDrive/Documents/GitHub/bitcoinops.github.io` look for the `.git/config`, e.g. for myself that would be:

```
cd Workspace/bitcoinops.github.io
vim .git/config
```

You can also use another text editor instead of `vim` of course.
This should open a configuration file that looks something like this:
image


I’ve marked the name of the “bitcoinops repository” in my config with an arrow.

**Pull request closed without merging**
