### PR TITLE
Optimizing currently included PNGs

### PR DESCRIPTION
**Pull request by 0xB10C**
Optimized with `optipng -o7`. Will rebase and add the PNGs from the currently open PRs (e.g. #179, #180, #181) once they are merged (if necessary). Happy to squash before merging this PR. 

refs #195

### CODE REVIEW

**Comment by 0xB10C** [comment]
> I optimized the compatibility matrix screenshots and logos for both the merged and unmerged compatibility commits. This PR finishes the job.
> > add the PNGs from the currently open PRs
> 
> Can you clarify this for me?

Oh sorry, I did't know you had already optimized the PNGs in the open PRs (i.e. the ones mentioned above). Then all PNGs should be optimized. 

> It looks like there are some images in /img/sponsors/ that were not changed. Were those already optimized?

The images in  /img/sponsors/ are JPEGs and not PNGs. Not sure if we can really do lossless optimization on these. But I'll have a look.

**Comment by jnewbery** [comment]
#200 is merged. Can this be closed?

**Comment by 0xB10C** [comment]
> > It looks like there are some images in /img/sponsors/ that were not changed. Were those already optimized?
>
> The images in img/sponsors/ are JPEGs and not PNGs. Not sure if we can really do lossless optimization on these. But I'll have a look.

The three JPEGs in `img/sponsors/`, `dong.jpg` and `newbery.jpg` in `img/team/` are already optimized according to the tool `jpegoptim` with default parameters.

> #200 is merged. Can this be closed?

I think this PR should cover all PNGs. I'll mark it as ready for review.

**Comment by harding** [comment]
ACK 773cd55692e0c6f1bef1a0710be167ac1bb43746 .  Lightly tested by looking at each modified image in my preferred image viewer (geeqie): `geeqie $( git diff HEAD^^^^ --name-only )` .  I didn't look at the originals for comparison, but each image matched what I'd expect from its file name.

Interestingly, both the original and modified copies of `img/posts/rbf-in-the-wild/rbf-green-multiple-bump-options.png` gave me a `Warning: Failed to decode Exif metadata.`.  The image decodes fine, otherwise.  Out of curiousity, @bitschmidty did you do something different for this image compared to the others you took for that blog post?

**Comment by 0xB10C** [comment]
Thank you for the review @harding!

**Comment by jnewbery** [comment]
Thanks @0xB10C and @harding :framed_picture:

**Pull request merged**
