### PR TITLE
Newsletters: add 191 (2022-03-16)

### PR DESCRIPTION
**Pull request by harding**
- [ ] Add lede, releases/RCs if any, and topic links @harding

### CODE REVIEW

**Review by bitschmidty — COMMENTED** [review]
Just one catch so far

**Comment by harding** [comment]
Edit made for @bitschmidty feedback (thanks!), releases section removed (none this week), topics updated, and lede added.

**Comment by bitschmidty** [comment]
ACK 2273618c07824583f79465ed698753a9d84ec8cc

**Comment by bitschmidty** [comment]
Noticed that Tapscript was used instead of tapscript and changed to adhere to the style guide: https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md#common-nouns

**Pull request merged**
