### PR TITLE
Newsletter 256 translate in french

### PR DESCRIPTION
**Pull request by Copinmalin**

### CODE REVIEW

**Review by bitschmidty — CHANGES_REQUESTED** [review]
@Copinmalin check the build log here for an error: https://app.netlify.com/sites/bitcoinops/deploys/64a58d494c7f2b00084486a8#L274

**Comment by Xekyo** [comment]
@Copinmalin: The anchor had an ‘e‘ instead of an ‘é’, changing the one letter fixed it in my local build.

**Comment by Copinmalin** [comment]
Thanks for your help @Xekyo

**Review by bitschmidty — APPROVED** [review]
ACK, thank you @Copinmalin !

**Pull request merged**
