### PR TITLE
Podcast: add 230 recap

### PR DESCRIPTION
**Pull request by bitschmidty**

### CODE REVIEW

**Review by murchandamus — COMMENTED** [review]
I haven’t read this completely, but it looks like it’s ready to go?

**Comment by bitschmidty** [comment]
Im ok to merge it (even if we are waiting on 230), if you are @murchandamus

**Comment by murchandamus** [comment]
Ah, so the transcription is there, but we don’t have the audio track?

**Comment by bitschmidty** [comment]
Sorry, I meant Im good to push 230 even if we are waiting on 231.

**Comment by murchandamus** [comment]
Ah yeah, it’s over half a year anyway, I don’t think it matters if one is missing in the order.

**Pull request merged**
