### PR TITLE
Newsletter 232 missing translation part in french

### PR DESCRIPTION
**Pull request by Copinmalin**

### CODE REVIEW

**Comment by Copinmalin** [comment]
please @bitschmidty if you can merge this request, because I miss to translate a part, thanks.

**Comment by bitschmidty** [comment]
@Copinmalin Would you mind removing the changes to the cs newsletter in 2199c64b7621efc21c564222019eddfb7f8c9dbe and any other files from other commits other than the 232/fr newsletter?

**Comment by bitschmidty** [comment]
Perhaps we can drop 2199c64b7621efc21c564222019eddfb7f8c9dbe altogether and just PR with 0925569e4318279cb57de4b41e89d7ad1451ac81 as the sole commit for this PR?

**Comment by Copinmalin** [comment]
@bitschmidty : Yes I think https://github.com/bitcoinops/bitcoinops.github.io/commit/2199c64b7621efc21c564222019eddfb7f8c9dbe was a wrong action from me, 

[0925569](https://github.com/bitcoinops/bitcoinops.github.io/pull/976/commits/0925569e4318279cb57de4b41e89d7ad1451ac81) seem to be complete and right.

you have a better experience than me, do what is best

**Comment by bitschmidty** [comment]
@Copinmalin for reference this is what I did. Perhaps there are better ways, but it works ok.

Checkout your branch locally then rebase on master:

> git reset --hard origin/master

Then cherry pick the commit that contains the updates:

> git cherry-pick 0925569e4318279cb57de4b41e89d7ad1451ac81

Then force push the changes to your remote branch.

Let me know if the final changes look correct to you before I merge.

**Comment by Copinmalin** [comment]
@bitschmidty I really need to do all these steps  😮

**Comment by Copinmalin** [comment]
@bitschmidty done, I hope it's correct 😅

**Comment by bitschmidty** [comment]
@Copinmalin I had actually already done those steps so it was ready to go.

I did the same 2 steps again and pushed to your branch so we should just have the one commit with the applicable changes. Does it look ok?

**Pull request merged**
