### PR TITLE
Translate newsletter-68 into Japanese

### PR DESCRIPTION
**Pull request by Ichiro0219**

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks @Ichiro0219 !

Are you checking the "Allow edits from maintainers" box when opening PRs? If you do that, we can do things like rebase on master or make minor edits without having to bother you.

**Comment by Ichiro0219** [comment]
> Awesome, thanks!
> 
> Tested that the page renders and the links look correct.
> 
> Would be nice to rebase on master which has the latests localization logics.

I rebased on master.
Could you check it?

> Thanks @Ichiro0219 !
> 
> Are you checking the "Allow edits from maintainers" box when opening PRs? If you do that, we can do things like rebase on master or make minor edits without having to bother you.

Thank you @jnewbery !
OK I will check the box next time.

**Comment by jnewbery** [comment]
Perfect. Thanks @Ichiro0219 . I'll wait for @bitschmidty to review this before merging.

**Comment by jnewbery** [comment]
Thank you! :tokyo_tower:

**Pull request merged**
