### PR TITLE
News109: signets use proof of work

### PR DESCRIPTION
**Pull request by jnewbery**
Thanks to @pinheadmz for reporting!

### CODE REVIEW

**Comment by harding** [comment]
Thanks @pinheadmz for reporting and @jnewbery for editing!

I agree the original is incorrect, but I think this edit could accidentally mislead people into thinking PoW plays a significant role in signets (it can, if you want, but it doesn't need to).  I think we can just drop the: "rather than using proof of work" so the text reads, "Signets are test networks where valid blocks are signed by trusted signers, [...]".  I think this is even more accurate as, in addition to valid blocks still needing a correct amount of PoW, they also need to follow all the other consensus rules---in Bitcoin, sufficient PoW doesn't eliminate the need to follow all the other rules, and in signet, a valid signature doesn't either.

**Comment by jnewbery** [comment]
> I think we can just drop the: "rather than using proof of work"

I agree. Thanks @harding!

**Comment by pinheadmz** [comment]
LGTM :+1:

**Comment by bitschmidty** [comment]
ACK

**Comment by harding** [comment]
ACK.  Thanks!

**Pull request merged**
