### PR TITLE
Update contributors

### PR DESCRIPTION
**Pull request by jnewbery**
- Rename 'associates' and 'principals' to 'contributors' 
- Remove roles 
- Update other affiliations 
- Add @glozow
- Add @azuchi

TODO:

- [x] Get agreement from @glozow and @azuchi. I think it makes sense to add them since they've made significant contributions over the last year.
- [ ] Get quote for @glozow
- [ ] Get quote for @azuchi

### CODE REVIEW

**Comment by glozow** [comment]
Concept ACK, thanks

**Comment by azuchi** [comment]
Concept ACK, thanks

**Comment by harding** [comment]
Concept ACK, thanks!

**Comment by glozow** [comment]
How about something like

As a developer, it feels like Bitcoin development innovates far too quickly for anyone to keep up! But engineering isn't enough to translate technological advancement into tangible improvements in a real person's life. Optech has been an incredible resource throughout my journey; I hope to help it be the same for the thousands of builders, designers, educators and trailblazers we'll need to bring Bitcoin to a billion people.

**Comment by azuchi** [comment]
How is this?

Bitcoin is a very exciting innovation, and many protocols and cryptographic improvements are still being proposed.
Understanding these is important for Bitcoin services and businesses, and Optech is one of the most useful resources for that. I hope to contribute to making Bitcoin technical information available to a wide range of people.

**Comment by jnewbery** [comment]
Both quotes look great to me. Thanks @glozow and @azuchi!

I've updated the branch to include those quotes.

**Review by bitschmidty — APPROVED** [review]
ACK, thanks @jnewbery !

**Pull request merged**
