### PR TITLE
Style Guide: prefer hardware signers over hardware wallets

### PR DESCRIPTION
**Pull request by jnewbery**

### CODE REVIEW

**Comment by jonatack** [comment]
ACK! 

Provided that people understand what we are referring to but education here is 👍

IDK if we (informally) need a transitory "hardware signers (hardware wallets)"

**Comment by bitschmidty** [comment]
ACK. I think its good to focus on such distinctions.

Also, agreed with the transitory parentheticals or the like.

**Comment by Xekyo** [comment]
ACK, I'd say that these devices are also more generally referred to as "Personal Hardware Security Modules", but "hardware signing devices" seems like a good improvement over "hardware wallets".

**Review by Xekyo — COMMENTED** [review]
ACK

Nit: I chafe a bit at describing them as "offline" since they often get plugged into a "hot device" to interact with the wallet. I'd describe them as personal hardware security modules, or dedicated hardware devices to extract the key storage and signing aspect from the wallet software.

**Comment by harding** [comment]
ACK

Maybe s/offline signing devices/dedicated key storage and signing devices/

**Comment by jnewbery** [comment]
> Nit: I chafe a bit at describing them as "offline" ...

> Maybe s/offline signing devices/dedicated key storage and signing devices/

Fixed. Thanks!

**Pull request merged**
