### PR TITLE
Update LICENSE

### LINKED ISSUE #45: Use explicit license
The homepage says, "all materials and documentation produced are placed in the public domain".  This is fine with me, but my non-lawyer [understanding](https://en.wikipedia.org/wiki/Public_domain#Dedicating_works_to_the_public_domain) is that public domain grants are not valid in all jurisdictions (particularly in the EU), so it's better to use a public domain grant with an explicit backup license like [CC0](https://creativecommons.org/publicdomain/zero/1.0/).

Although CC0 has a no-warranty clause, my (again non-lawyer) interpretation is that it doesn't necessarily apply if the court decides to enforce the public domain grant, possibly opening dedicators to lawsuits for inaccurate documentation.  For that reason, I slightly prefer MIT, which is almost as liberal as public domain but requires the no-warranty statement be retained with all copies.

For comparison, Bitcoin Core, Bitcoin.org, and BitcoinCore.org all use the MIT license for their documentation, and the Bitcoin Wiki uses CC-SA for most content.  My personal preferred license is CC-SA, but I think I'm probably in the minority there in the Bitcoin community and any [FSF-vetted free license](https://www.gnu.org/licenses/license-list.en.html) is ultimately fine by me.

(This issue arose in my mind as I'm about to reuse a couple sentences I wrote for previous newsletters on BitcoinCore.org.)

### PR DESCRIPTION
**Pull request by jnewbery**
Adds MIT License.

Since this changes the license, I guess we need approval from all contributors: @harding , @jamesob , @moneyball 

fixes #45

### CODE REVIEW

**Comment by harding** [comment]
ACK 586eb0d  Thanks!

**Comment by jamesob** [comment]
ACK

**Comment by moneyball** [comment]
ACK

**Comment by jnewbery** [comment]
AJ Towns has agreed to his contributions being released under the MIT license:

```
13:15 <jnewbery> Hi AJ. Can you confirm that you're happy for the Xapo consolidation article to be released under MIT license? (I assume yes, but the license wasn
13:15 <jnewbery> 't on the website when you sent the text to me, so I should check with you.)
22:00 <aj> yes, that sounds fine
```

All contributors have now ACKed, so I'll merge.

**Pull request merged**
