### PR TITLE
Newsletter-198: Add Czech translation

### PR DESCRIPTION
**Pull request by nechteme**
Translation of Newsletter 198 into Czech language, first of its kind. Hope more will follow.

In the absence of translations of topics, I appended a Glossary section to the newsletter where I briefly explain some of the terms, for which there would otherwise be a dedicated topic page.

### CODE REVIEW

**Comment by bitschmidty** [comment]
@nechteme wow, thank you for this! Ive built locally and checked the links.

I think the footnotes are a good short explanation. What do you think of adding a link in each footnote to the English topic for readers that wish to learn more?

**Comment by nechteme** [comment]
> adding a link in each footnote to the English topic

Good idea! I added links to topics and BIPs.

**Review by Xekyo — APPROVED** [review]
Thanks, @nechteme, this looks amazing.

Built the site locally, tested all the links in the Czech newsletter, and had a Czech acquaintance take a look who found it to be "totally legit". Assuming that @nechteme thinks this is ready to go, I think we can merge this.

Having had a look at the `Makefile` today, I was wondering whether we should perhaps also flush the indices for other languages as we do for English when building.

**Comment by nechteme** [comment]
Yes, please. Went through the text once more and it is ready.

**Comment by harding** [comment]
Lightly tested ACK. Reviewed the diff, built the site locally, skimmed the google translate of the newsletter and added index pages.  It all looks good to me, thanks so much @nechteme !

**Review by bitschmidty — APPROVED** [review]
ACK e245c8dae1f5356814a61f17e5e4d4f24b82ac63

**Pull request merged**
