### PR TITLE
Update "about" page

### PR DESCRIPTION
**Pull request by jonatack**
Have been inactive here since a bit more than nine months, so it seems best to remove my profile.

### CODE REVIEW

**Comment by bitschmidty** [comment]
@moneyball @jonatack Take a look at this alternative based on Steves Alum idea
https://github.com/bitcoinops/bitcoinops.github.io/pull/761

**Comment by Xekyo** [comment]
I'm good with either, but would prefer the alumni section. What do you think, @jonatack?

**Comment by jonatack** [comment]
Sorry for not responding, will look/test soon!

**Comment by jonatack** [comment]
> I'm good with either, but would prefer the alumni section. What do you think, @jonatack?

@Xekyo SGTM.

**Pull request closed without merging**
