### PR TITLE
Newsletter-202: add Hindi translation

### PR DESCRIPTION
**Pull request by shaavan**

### CODE REVIEW

**Comment by shaavan** [comment]
Updated from 455ac8f to ba2d813 [[Diff](https://github.com/bitcoinops/bitcoinops.github.io/compare/455ac8f..ba2d813)]

- Fixes permalink from `/en/...` to `/hi/...`.
- Removes trailing spaces.

**Comment by Xekyo** [comment]
Hi shaavan, thank you for translating the newsletter to Hindi. I've added the category pages for blog, newsletter and publications so that these pages will also show up for Hindi. I quickly looked over an automatic translation of your content which looked reasonable, but I'll try to find a reviewer to look your contribution over so we can hopefully merge it quickly.

**Review by sanket1729 — APPROVED** [review]
ACK the Hindi translation. I don't know if it is the best wording (Hindi is my third language), but I can ACK the grammar, correctness, and completeness of the translation.

**Review by Xekyo — APPROVED** [review]
Thanks, @sanket1729!

I've built this PR locally, checked the links in the newsletter, tested that the newsletter shows up on the newsletter and publications page in Hindi. Looks all good to me.

**Review by bitschmidty — APPROVED** [review]
tACK (built, previewed, checked links)!

Thank you very much for this @shaavan !

**Pull request merged**
