### PR TITLE
Newsletter-73:Translate into Japanese

### PR DESCRIPTION
**Pull request by Ichiro0219**

### CODE REVIEW

**Comment by AkioNak** [comment]
@Ichiro0219 I think some words/phrases are broken and should be corrected. fa7ce10

**Comment by bitschmidty** [comment]
@AkioNak Can you comment on the lines which should be corrected?
https://github.com/bitcoinops/bitcoinops.github.io/pull/291/files

**Comment by AkioNak** [comment]
@bitschmidty It seems "work in progress" version. I think @Ichiro0219 has his newest one.

**Comment by Ichiro0219** [comment]
@bitschmidty 
I fixed some words/phrases and pushed again.

**Comment by AkioNak** [comment]
@Ichiro0219 @bitschmidty I have nothing to point out.

**Comment by bitschmidty** [comment]
ACK 

@Ichiro0219 thanks for the translation and @AkioNak thank you for the review!

**Pull request merged**
