### PR TITLE
Newsletter 76:Translate into Japanese

### PR DESCRIPTION
**Pull request by Ichiro0219**

### CODE REVIEW

**Comment by AkioNak** [comment]
I think Travis has failed due to ```gem update --system``` overwrote ```bundle(r)```.
https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds/628560320#L235-L247
(Currently, #282 is also in the same situation)

In recent success build,  a conflict occured (and perhaps it remained 1.17.3) .
https://travis-ci.org/bitcoinops/bitcoinops.github.io/builds/627456462#L224-L234

I think it is better to fix ```.travis.yml``` or ```Gemfile.lock``` with anather PR.

**Comment by jnewbery** [comment]
Travis failure was unrelated to this PR. I've merged #307 and rerun the build successfully.

**Comment by bitschmidty** [comment]
ACK

@Ichiro0219 Looks good to me! 

Can you rebase on master and squash commits? (or give me permission to commit to cg repository)

Note: as we have change some dependencies, when building you might need to run `bundle install` first

**Comment by Ichiro0219** [comment]
> ACK
> 
> @Ichiro0219 Looks good to me!
> 
> Can you rebase on master and squash commits? (or give me permission to commit to cg repository)
> 
> Note: as we have change some dependencies, when building you might need to run `bundle install` first
@bitschmidty Done!

**Comment by bitschmidty** [comment]
LGTM thanks for the translation @Ichiro0219 !

**Pull request merged**
