### PR TITLE
Newsletter-206: Add Chinese translation

### PR DESCRIPTION
**Pull request by hulatown**
- Newsletter-206: Add Chinese translation

### CODE REVIEW

**Comment by bitschmidty** [comment]
@hulatown Can you change this to 2 commits:

- one for 206
- one for 204 changes

I dont believe I have permissions to do this and commit back to your repository myself.

**Comment by hulatown** [comment]
> 



> @hulatown Can you change this to 2 commits:
> 
> * one for 206
> * one for 204 changes
> 
> I dont believe I have permissions to do this and commit back to your repository myself.

**Comment by Xekyo** [comment]
Just a heads-up, Github interprets the string "#<number>" in commit message as links to issues and pull requests in the same repository. We usually just start commits for specific newsletters with "News###:".

**Comment by hulatown** [comment]
> Just a heads-up, Github interprets strings "#<number>" in commit messages as links to issues and pull requests in the same repository. I think that you mean to refer to the newsletter issue, not a pull request or repository issue. We usually just start commits for specific newsletters with "News###:". Using that would also travel well between repositories.

I see. Will follow this guide! Thanks!

**Comment by bitschmidty** [comment]
> > There are still two commits involving the 204 newsletter, which is causing a potential merge issue, can you drop those changes at retain the 206 commits?
> 
> I think the commits have been reverted and could be merged. But anyway, let me try by closing this and creating a new PR.

github was disallowing the merge and the new PR seemed to work so either way, good now!

**Pull request closed without merging**
