### PR TITLE
Contributor Updates

### PR DESCRIPTION
**Pull request by bitschmidty**
Thank you @Copinmalin @hulatown @jirijakes for your contributions.

### CODE REVIEW

**Comment by Copinmalin** [comment]
Thank you very much for the recognition of my commitment and especially for the support and kindness.

**Comment by jirijakes** [comment]
Thanks a lot! 🙏

**Comment by harding** [comment]
Added a commit to update my profile image, considering the previous image was more than 15 years old.

Changes to contributors.yml LGTM and I previewed changes locally.  I'm ACK on this if @murchandamus or @adamjonas are ok with the text change to about.md.

> Thank you @Copinmalin @hulatown @jirijakes for your contributions.

Here!  Here!  Thank you so much!

**Comment by hulatown** [comment]
Thank you so much for the recognition of our work!

**Comment by murchandamus** [comment]
Changes seem fine to me, except that I would refer the question about Chaincode to @adamjonas.

**Comment by murchandamus** [comment]
I updated my github account and my picture

**Comment by murchandamus** [comment]
Ah thanks, I was just doing the same.

**Comment by adamjonas** [comment]
Ugh. It's technically true. ACK on my bit.

**Pull request merged**
