### PR TITLE
Add motivation quotes

### LINKED ISSUE #11: Add team member information
John:
"I started Optech because if Bitcoin is to be successful, then one of the fundamental challenges facing Bitcoin services and businesses will be how to maximize customer utility by making efficient use of the blockchain. Helping Bitcoin ecosystem players adopt scaling techniques and technologies is one of the most effective ways we can help Bitcoin scale today."

James:
"If Optech succeeds, the Bitcoin ecosystem will have higher rates of technical coordination and understanding; businesses will gain technical insight from the opensource community, and opensource engineers will understand the challenges that industrial users of Bitcoin face. This may benefit everyone working with and relying upon Bitcoin."

Steve:
“I am excited to help Bitcoin Optech Group make a meaningful contribution to Bitcoin. I’m looking forward to working with businesses to develop implementation best practices and to build a bridge between businesses and the open source community.”

### PR DESCRIPTION
**Pull request by jnewbery**
closes #11 

Adds motivation quotes. I don't think this looks very good at the moment. Perhaps we should use the two column layout from #9.

Also need to add thumbnails and quotes from @harding and @marcinja (assuming you guys want that?)

### CODE REVIEW

**Comment by harding** [comment]
I feel silly making up quotes, but here's one that sounds suitably corny:

> The terrible thing about a consensus system like Bitcoin is that every on-chain action we perform affects every other user of the system.  That makes all of us neighbors, so we're faced with the choice of either being the bad neighbors who complain endlessly about each other or the good neighbors who work together to solve problems and find ways to coexist in harmony.

**Comment by jnewbery** [comment]
Updated the about page to use the two-column layout and added avators & quotes.

Ready for review.

@marcinja - do you want to add a quote to the about page?

**Comment by marcinja** [comment]
Sure. Here's my quote:

> I'm interested in helping make Bitcoin better, and an important step forward is getting the community to use Bitcoin more efficiently. I hope that Optech can help coordinate this effort, and others, to make it as great as possible.

**Comment by jnewbery** [comment]
Taken @harding diff, added @marcinja quote and rebased

**Comment by jnewbery** [comment]
@jamesob @moneyball - do you mind testing/reviewing?

**Comment by jamesob** [comment]
Tested ACK - looks great!

**Comment by jamesob** [comment]
@harding's quote is :100:.

**Pull request merged**
