### PR TITLE
Newsletter 122: increase forward fee (suggestion by joostjager, thanks!)

### PR DESCRIPTION
**Pull request by harding**
@joostjager [noted](https://twitter.com/joostjgr/status/1323984013690810368) that the diagram from this week's newsletter should show different fees for different hops.  Using @t-bast's [original email](https://lists.linuxfoundation.org/pipermail/lightning-dev/2020-October/002862.html) as a template, this PR updates to use the numbers he uses (1 "msat" == 10 pBTC)

```text
* A sends an HTLC to B:
* `hold_grace_period = 100 sec`
* `hold_fees = 5 msat`
* `next_hold_grace_period = 90 sec`
* forward upfront payment: 1 msat is deduced from A's main output and added
to B's main output
* backwards upfront payment: 5 msat are deduced from B's main output and
added to A's main output
* B forwards the HTLC to C:
* `hold_grace_period = 90 sec`
* `hold_fees = 6 msat`
* forward upfront payment: 1 msat is deduced from B's main output and added
to C's main output
* backwards upfront payment: 6 msat are deduced from C's main output and
added to B's main output
```

### CODE REVIEW

**Comment by t-bast** [comment]
Thanks! You should also note that the forward fee decreases moderately at each hop (as pointed out by Joost after I sent my proposal). I currently only have it in a comment in https://github.com/t-bast/lightning-docs/blob/master/spam-prevention.md#bidirectional-upfront-payment, I need to update it to reflect it better.

**Comment by t-bast** [comment]
For example we could have a forward fee of 30 pBTC in the A -> B channel and 20 pBTC in the B -> C channel.

**Comment by harding** [comment]
Updated to include both incrementing and decrementing fees per comments here and in the Twitter thread.  I removed the additional text commentary as I felt it was expanding the scope of the published newsletter too much.

Note: I'm leaving for a trip in a few minutes and won't have the ability to make additional edits until Friday.  Sorry.

**Review by t-bast — APPROVED** [review]
That sounds good, that shows the mechanisms without needing additional text. :rocket:

**Comment by jnewbery** [comment]
Thanks @harding , and thanks @joostjager and @t-bast for review!

**Pull request merged**
