### PR TITLE
Translate Newsletter#69 into Japanese

### PR DESCRIPTION
**Pull request by Ichiro0219**

### CODE REVIEW

**Comment by bitschmidty** [comment]
@Ichiro0219 can you allow edits from maintainers? I think I would be able to push commits (if needed) if you set that. 

In this case there is an extra space which is causing the build to fail.

See screenshot here for example:
https://user-images.githubusercontent.com/6248932/61183973-6989b780-a648-11e9-86b3-b17089acd1e4.png

**Comment by Ichiro0219** [comment]
> @Ichiro0219 can you allow edits from maintainers? I think I would be able to push commits (if needed) if you set that.
> 
> In this case there is an extra space which is causing the build to fail.
> 
> See screenshot here for example:
> https://user-images.githubusercontent.com/6248932/61183973-6989b780-a648-11e9-86b3-b17089acd1e4.png
@bitschmidty 
I checked the box "Allow edits from maintainers."
Can you edit it?

**Comment by bitschmidty** [comment]
@Ichiro0219 that did not work for me.

I have instead submitted a PR to your branch here:
https://github.com/cryptogarageinc/bitcoinops.github.io/pull/1

**Comment by jnewbery** [comment]
Can you squash the commits down into a single commit before merge please?

**Comment by Ichiro0219** [comment]
> Can you squash the commits down into a single commit before merge please?
I ’m sorry to trouble you.I squashed the commits.
Could you check it?

**Comment by Ichiro0219** [comment]
> Can you squash the commits down into a single commit before merge please?
I ’m sorry to trouble you.I squashed the commits.
Could you check it?

**Comment by bitschmidty** [comment]
LGTM @Ichiro0219 

tACK fec12cc4d35816486c1384eb643c40c367f4671f

**Pull request merged**
