### PR TITLE
Compat: reactivate schema checker

### PR DESCRIPTION
**Pull request by harding**
Based on top of #185, ignore first two commits..

This was previously included as part of #168 but it seems to prevent Netlify from successfully building both previews and production deployments of the site so it was disabled in #174.  To debug, it'd be useful to get a copy of the Netlify build log for the preview from @adamjonas 

This runs for me locally and it previously ran successfully on Travis.

### CODE REVIEW

**Comment by bitschmidty** [comment]
@harding 

I pushed this to my netlify instance as is and it failed to build. (log attached)

I [took out the "BUNDLED WITH" directive in Gemfile.lock](https://github.com/bitschmidty/bitcoinops.github.io/commit/87d3a2a3d6a9d9e61f953f22cea0c725660e33ed) and netlify built correctly. (log attached)

[netlify-successful-build.txt](https://github.com/bitcoinops/bitcoinops.github.io/files/3486595/netlify-successful-build.txt)
[netlify-failed-build.txt](https://github.com/bitcoinops/bitcoinops.github.io/files/3486596/netlify-failed-build.txt)

**Comment by harding** [comment]
@bitschmidty I cherry picked your commit but it doesn't seem to have changed things for the PR preview here.  I think we still need logs from the bitcoinops netlify build.

**Comment by adamjonas** [comment]
@harding 

```

**Comment by harding** [comment]
I give up.  It appears to be something specific to our Netlify instance (rather than their system in general) that I can't debug myself.  Until this is resolved, it appears that we're stuck with the ruby gem dependencies we have cached on Netlify and can't add or upgrade any.  For now, we can just skip having this extra test.

For reference, we seem to be failing here: https://github.com/netlify/build-image/blob/trusty/run-build-functions.sh#L318

**Pull request closed without merging**
