### PR TITLE
Newsletters: add #43 (2019-04-23)

### PR DESCRIPTION
**Pull request by harding**
Notes:
- Makes a one-word edit to a previous newsletter after I couldn't find text I knew I'd written by the keyword I was expecting.  (If anyone objects, I'm 100% ok reverting that change.)
- The BIP158 bullet is in the News section because, when I started writing it, I didn't think we had any other news.  However, I remembered the LND release, which is actual news.  If anyone would like, I'm happy to move the BIP158 bullet to the notable code changes section that might be more appropriate.
- I won't be available for edits Monday afternoon/evening, so please feel free to make any edits y'all think are appropriate.  (Remember the editors razor: if in doubt, delete.)  I will be available early Tuesday morning, so please feel free to leave me things to fix or review then.

### CODE REVIEW

**Comment by jnewbery** [comment]
utACK c13a6837d2f05a1fe1da6822b8a353e225833636. No review comments!

> Makes a one-word edit to a previous newsletter after I couldn't find text I knew I'd written by the keyword I was expecting.

Change looks good to me :+1: 

> The BIP158 bullet is in the News section because, when I started writing it, I didn't think we had any other news. However, I remembered the LND release, which is actual news. If anyone would like, I'm happy to move the BIP158 bullet to the notable code changes section that might be more appropriate.

No, I think this is interesting enough to be in the **News** section

**Comment by moneyball** [comment]
BIP157 not BIP158, right?

**Comment by harding** [comment]
Force-pushed a small edit to the main text and a detailed footnote explaining the differences between 157, 158, and how the current PR implements parts of both of them (but mainly 158 IMO).

**Comment by jnewbery** [comment]
Made some minor edits to the footnote: https://github.com/bitcoinops/bitcoinops.github.io/pull/137/commits/2f070d730fda3d22aa4cbacc066738ea3fb7290e

**Comment by jnewbery** [comment]
Squashed to aa673ccaf76d13a0edfbba401d84f16b3cdba7e2

**Comment by harding** [comment]
Post-merge ACK on the edits.  Thanks, and thanks for the reviews!

**Pull request merged**
