### PR TITLE
Newsletter-293: translate into Chinese

### PR DESCRIPTION
**Pull request by hulatown**

### CODE REVIEW

**Review by bitschmidty — APPROVED** [review]
ACK, thank you @hulatown !

**Review by bitschmidty — CHANGES_REQUESTED** [review]
@hulatown actually the translation looked good, but I see there are other commits and file changes here, can you take a look?

I think you can just rebase on master and be fine here.

**Comment by hulatown** [comment]
> @hulatown actually the translation looked good, but I see there are other commits and file changes here, can you take a look?
> 
> I think you can just rebase on master and be fine here.

Rebased! It seems that it was affected by some forced push before, but it looks fine now. Can you please check again?

**Review by bitschmidty — APPROVED** [review]
ACK, thank you @hulatown !

**Pull request merged**
