### PR TITLE
Newsletter-160:Translate into Japanese

### PR DESCRIPTION
**Pull request by azuchi**

### CODE REVIEW

**Review by bitschmidty — APPROVED** [review]
ACK, thanks @azuchi 

Note: keeping an eye on https://github.com/bitcoinops/bitcoinops.github.io/pull/622 once it is merged would be nice to have changes apply to Japanese 160 as well.

**Comment by azuchi** [comment]
Noted. I will update when merged.

**Comment by bitschmidty** [comment]
@azuchi this just got merged, FYI: 
https://github.com/bitcoinops/bitcoinops.github.io/pull/622

**Comment by azuchi** [comment]
@bitschmidty I created #623 to apply #622 change.

**Pull request merged**
