### PR TITLE
Newsletter-141:Translate into Japanese

### PR DESCRIPTION
**Pull request by azuchi**
I will update the `[news140 recovery]` link after the merge of #530.

### CODE REVIEW

**Comment by bitschmidty** [comment]
@azuchi https://github.com/bitcoinops/bitcoinops.github.io/pull/530 is now merged

**Comment by azuchi** [comment]
@bitschmidty Thanks! I updated.

**Comment by bitschmidty** [comment]
@AkioNak do you have a moment for review? Or we can merge and address any feedback later

**Comment by AkioNak** [comment]
@bitschmidty @adamjonas I am sorry. I don't have enough time for a review this week.
 I hope I will give some feedbacks next week.

**Comment by bitschmidty** [comment]
No problem, thanks for letting us know. Ill merge this PR

**Pull request merged**
