### PR TITLE
Update CONTRIBUTING.md with review tips

### PR DESCRIPTION
**Pull request by jnewbery**
Add tip about reviewing topic page updates.

### CODE REVIEW

**Comment by harding** [comment]
This looks fine to me (sans linter failure), but if you want, I think you could make it compatible with both local previews and remote previews.  E.g., for a remote preview:

    BASEURL="https://deploy-preview-474--bitcoinops.netlify.app/" ; git diff master _topics/ | sed "s'url: /'url: ${BASEURL:-http://localhost:4000/}'" | colordiff | less -r

For a local preview, just set BASEURL to empty (or omit it if you've never used it in that shell before):

    BASEURL="" ; git diff master _topics/ | sed "s'url: /'url: ${BASEURL:-http://localhost:4000/}'" | colordiff | less -r

(`${variable_name:-default_value}` appears to be POSIX shell, so it should work even with some non-bash shells, but I haven't 100% confirmed that.)

**Comment by jnewbery** [comment]
Thanks for the review, Dave! I've pushed a fix to the linter issue and updated the shell command.

**Review by bitschmidty — APPROVED** [review]
tACK b37d18b20c170fc82c1ff2fce932f9e466cb5476

- Modified a topic md file locally
- Ran local diff command and validated output
- Ran remote/PR command
- `make production` to ensure no build errors

(on macOS)

**Comment by jnewbery** [comment]
Thanks @bitschmidty!

**Pull request merged**
