### PR TITLE
 Newsletter 225: Translate to Fench 

### PR DESCRIPTION
**Pull request by Copinmalin**

### CODE REVIEW

**Comment by Copinmalin** [comment]
Hello @bitschmidty 
thanks for your review

**Review by bitschmidty — COMMENTED** [review]
Pushed a few corrections

- .md missing from the file name
- some french #anchor links not working with accent markets, correct
- some of the BOLTs # links were not working (were BOLT instead of BOLTs)
- PR review section malformed causing build error

Let me know how it looks @Copinmalin

**Comment by Copinmalin** [comment]
hello @bitschmidty , 

I have a problem in line 165/166 with 

`[attaque par
  usurpation de paiement][]`

doesn't work 

Can you help me please ?

**Comment by bitschmidty** [comment]
> hello @bitschmidty ,
> 
> I have a problem in line 165/166 with
> 
> `[attaque par usurpation de paiement][]`
> 
> doesn't work
> 
> Can you help me please ?

Sorry, I had a fix for this as well but hadnt pushed it yet. See the latest commit (https://github.com/bitcoinops/bitcoinops.github.io/pull/933/commits/bb9e6f46b00032b453e7822d76646959b72e0974) for the fix. The issue is that when using a link like [attaque par usurpation de paiement][], it will look for a reference link at the bottom of "[attaque par usurpation de paiement]" and since the english version of the link was in the references still "[spoof payment attack]" the link was broken.

**Comment by bitschmidty** [comment]
@Copinmalin for some reason github closed this PR when I pushed the changes, so I opened another PR with the same content:

https://github.com/bitcoinops/bitcoinops.github.io/pull/933

**Comment by Copinmalin** [comment]
OK I understand, 

Thanks for your help 

see you next week ;-)

**Pull request closed without merging**
