### PR TITLE
newsletter-70:add Japanese translation

### PR DESCRIPTION
**Pull request by Ichiro0219**

### CODE REVIEW

**Comment by jnewbery** [comment]
Thanks for the translation @Ichiro0219 ! The branch failed to build because the markdown linted found trailing whitespace on line 42. I've fixed it locally, but I can't push to your branch. Can you verify that you've checked the **allow edits from maintainers** box in the pull request?

image

**Comment by Ichiro0219** [comment]
> Thanks for the translation @Ichiro0219 ! The branch failed to build because the markdown linted found trailing whitespace on line 42. I've fixed it locally, but I can't push to your branch. Can you verify that you've checked the **allow edits from maintainers** box in the pull request?
> 
> image
I'm sorry to bother you.
I checked the box and I don't know why it dosen't work.
I will fix and push again.

**Comment by jnewbery** [comment]
Please don't apologise! We're very grateful that you're contributing these translations 😄 

I wonder if it's perhaps because you're using the [cryptogarageinc repository](https://github.com/cryptogarageinc/bitcoinops.github.io/tree/newsletter-70) to open these PRs. Maybe if cloned this repo to your own **Ichiro0219** repository and then opened the  PR from there we'd be able to push to it? (I'm just guessing)

**Comment by Ichiro0219** [comment]
> Please don't apologise! We're very grateful that you're contributing these translations 😄

Thank you John😄
> 
> I wonder if it's perhaps because you're using the [cryptogarageinc repository](https://github.com/cryptogarageinc/bitcoinops.github.io/tree/newsletter-70) to open these PRs. Maybe if cloned this repo to your own **Ichiro0219** repository and then opened the PR from there we'd be able to push to it? (I'm just guessing)

Mmm, I will check.

**Pull request merged**
